APP_NAME="iOExternal"
APP_ENV=local
APP_KEY=base64:HgIPmHoSb/6hgNVs3L5ekyYDmrcWx0ln7H1c1AMydfI=
APP_DEBUG=true
APP_URL=https://ioexternal.azurewebsites.net

L5_SWAGGER_CONST_HOST=https://ioexternal.azurewebsites.net
APP_API_URL = https://ioexternal.azurewebsites.net
APP_PORTAL_URL = https://ioexternal.azurewebsites.net
APP_ADMIN_URL = https://ioexternal.azurewebsites.net

LOG_CHANNEL=stack

DB_CONNECTION=mysql
DB_HOST=ak-rw-01.mysql.database.azure.com
DB_PORT=3306
DB_DATABASE=ioexternal
DB_USERNAME=aktMaster@ak-rw-01
DB_PASSWORD=App2Grid@2020
MYSQL_SSL=true

IPOSTA_DB_CONNECTION=mysql
IPOSTA_DB_HOST=ak-rw-01.mysql.database.azure.com
IPOSTA_DB_PORT=3306
IPOSTA_DB_DATABASE=iposita
IPOSTA_DB_USERNAME=aktMaster@ak-rw-01
IPOSTA_DB_PASSWORD=App2Grid@2020
IPOSTA_MYSQL_SSL=true


BROADCAST_DRIVER=log
CACHE_DRIVER=array
QUEUE_CONNECTION=sync
SESSION_DRIVER=file
SESSION_LIFETIME=120

REDIS_HOST=127.0.0.1
REDIS_PASSWORD=null
REDIS_PORT=6379

MAIL_MAILER=smtp
MAIL_HOST=smtp.mailtrap.io
MAIL_PORT=2525
MAIL_USERNAME=c01d3de3c55595
MAIL_PASSWORD=059a97017e2ebf
MAIL_ENCRYPTION=tls

TWILIO_SID="ACbe38e11b11120944907055b7f2c68815"
TWILIO_AUTH_TOKEN="c47abb83b505e2ab5192ad7abdd516f6"
TWILIO_VERIFY_SID="VAcb6452ce7ff6151be94453aacd3c44ee"


AWS_ACCESS_KEY_ID=
AWS_SECRET_ACCESS_KEY=
AWS_DEFAULT_REGION=us-east-1
AWS_BUCKET=

PUSHER_APP_ID=1249055
PUSHER_APP_KEY=9585f2a65f2d29c7bc78
PUSHER_APP_SECRET=1b1123935cf0ba5868e8
PUSHER_APP_CLUSTER=mt1

MIX_PUSHER_APP_KEY="${PUSHER_APP_KEY}"
MIX_PUSHER_APP_CLUSTER="${PUSHER_APP_CLUSTER}"

GRID_CODE_BASE_URL=https://papi.gridweb.net:8077
GRID_CODE_SECRET_KEY=Z3JpZGF1dGg6YTQxNjA2NjUtODUxZC00ZGViLTk1YTAtZTE0NGI5MjBjMDMyOkdyaWQgUk4=
IP_STACK_ACCESS_KEY=7c7a5f418aa0e0b9ca2cae789a52ff2d

MYSQL_ATTR_SSL_KEY=site\wwwroot\ssl\BaltimoreCyberTrustRoot.crt.pem
#AZURE_STORAGE_NAME=ganza1
#AZURE_STORAGE_KEY=H39Nu/lKt8egO9rmffe+K0h98OAJ0e7npVTSExGjo8TRak7QY7syMLcudxQhnXbHTxtrhOmWm+KcaqilnrIXnQ==
#AZURE_STORAGE_CONTAINER=ganza
#AZURE_STORAGE_URL=https://ganza1.blob.core.windows.net/
#GOOGLE_API_KEY=AIzaSyDJ-10ywLsARBlXZnKxnKrc2eHIlwl0YVg

#gridbusinessdb
#server admin:gridbusiness
#password:Gb@12345

GRIDNAV_BASE_URL=https://portal-gridbusiness.azurewebsites.net
IPOSTA_BASE_URL=https://ipositaondemand.rw

#687747f1f9ff1e863d46355339827c43401e108e9a83b6f21ccf72b172122d89

